DROP TABLE IF EXISTS items;
DROP SEQUENCE IF EXISTS item_id_seq;
DROP TABLE IF EXISTS customers CASCADE;
DROP SEQUENCE IF EXISTS customer_id_seq;
DROP TABLE IF EXISTS orders;
DROP SEQUENCE IF EXISTS order_id_seq;